name: sahyadri_hacknight
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.4.1
  cloud_firestore: ^5.4.1
  google_fonts: ^6.2.0
  flutter_native_splash: ^2.4.1
  flutter_launcher_icons: ^0.14.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/LyBry-Transparent.png


flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/LyBry.png"
  adaptive_icon_background: "assets/bg.png"
  adaptive_icon_foreground: "assets/LyBry-Transparent.png"

flutter_native_splash:
  color: "#ffffff"
  color_dark: "#ffffff"
  image: "assets/LyBry.png"
  image_dark: "assets/LyBry.png"

  android_12:
    color: "#ffffff"
    color_dark: "#ffffff"
    image: "assets/LyBry.png"
    image_dark: "assets/LyBry.png"